### ISSUE TITLE
How to use a custom error handler?

### ISSUE THREAD

**Issue by arnlen** [iangreenleaf/githubot#30]
I would like to catch merging branch errors.
Here is my code:

```ruby
github  = require("githubot")(robot, errorHandler: (callback) -> 
    console.log ("Print this: #{callback}"))
app     = 'user/repo'

github.branches(app).merge "master", into: "production", (mergeCommit) ->
  [...]
```

And the response in my console:

```
[Mon Jun 27 2016 16:44:09 GMT+0200 (CEST)] ERROR Nothing to merge
```

Do you have a code example of a custom error handler?
If you provide it, I would be able to update your documentation with a working example.

**Comment by iangreenleaf** [comment]
The way it's set up right now, the error still gets logged if you specify a handler. But the handler *should* be getting called… if it's still not working, you could try it this way and see if that changes anything (but, either way *should* work so it would be a bug):

```ruby
github  = require("githubot")(robot)
github.handleErrors (callback) -> 
    console.log ("Print this: #{callback}"))
app     = 'user/repo'

github.branches(app).merge "master", into: "production", (mergeCommit) ->
  # ...
```

**Comment by arnlen** [comment]
Great! It works! 👍 
I create a PR to improve doc on this point.

Thx a lot mate.
